"""Add rate limit table for limit login

Revision ID: 3ae81edd27c4
Revises: d20f759b8812
Create Date: 2025-11-04 19:44:19.663696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae81edd27c4'
down_revision: Union[str, Sequence[str], None] = 'd20f759b8812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_endpoint_time', 'rate_limits', ['endpoint', 'attempted_at'], unique=False)
    op.create_index('idx_identifier_endpoint_time', 'rate_limits', ['identifier', 'endpoint', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_rate_limits_attempted_at'), 'rate_limits', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_rate_limits_id'), 'rate_limits', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limits_identifier'), 'rate_limits', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limits_identifier'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_id'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_attempted_at'), table_name='rate_limits')
    op.drop_index('idx_identifier_endpoint_time', table_name='rate_limits')
    op.drop_index('idx_endpoint_time', table_name='rate_limits')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
